{
 "title": "Slurm Overview",
 "description": "slurm-exporter",
 "tags": [
  "slurm",
  "dashboard"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Cluster Nodes",
   "type": "row",
   "description": "Cluster Nodes",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Nodes Available",
   "type": "stat",
   "description": "List of all nodes available in SLURM",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "slurm_nodes_alloc + slurm_nodes_comp + slurm_nodes_drain + slurm_nodes_idle + slurm_nodes_maint + slurm_nodes_mix + slurm_nodes_resv",
     "legendFormat": "available nodes"
    }
   ]
  },
  {
   "title": "Node state",
   "type": "timeseries",
   "description": "SLURM nodes state over time",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "{__name__=~\"slurm_nodes_.*\"} > 0",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Nodes Allocated",
   "type": "stat",
   "description": "List of all nodes allocated in SLURM",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "slurm_nodes_alloc + slurm_nodes_mix",
     "legendFormat": "available nodes"
    }
   ]
  },
  {
   "title": "CPU cores allocation",
   "type": "row",
   "description": "CPU cores allocation",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPUs Available",
   "type": "stat",
   "description": "Total CPUs available",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "slurm_cpus_total - slurm_cpus_other",
     "legendFormat": "available cpus"
    }
   ]
  },
  {
   "title": "CPUs Allocated per Partition",
   "type": "timeseries",
   "description": "CPUs Allocated per partition over time",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "slurm_partition_cpus_allocated", "legendFormat": "{{partition}}" },
    { "expr": "slurm_cpus_total", "legendFormat": "total" }
   ]
  },
  {
   "title": "CPUs Allocated",
   "type": "stat",
   "description": "Total CPUs allocated",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "slurm_cpus_alloc", "legendFormat": "allocated cpus" }
   ]
  },
  {
   "title": "Top Accounts by CPUs running",
   "type": "bargauge",
   "description": "Top 10 acounts by amount of CPUs running",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sort_desc(sum by (account) (slurm_account_cpus_running)))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPUs running per Account",
   "type": "timeseries",
   "description": "CPUs running per account over time",
   "gridPos": { "h": 10, "w": 8, "x": 3, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "slurm_account_cpus_running{account!~'none'}",
     "legendFormat": "{{account}}"
    }
   ]
  },
  {
   "title": "Top Users by CPUs running",
   "type": "bargauge",
   "description": "Top 10 users by amount of CPUs running",
   "gridPos": { "h": 10, "w": 3, "x": 11, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sort_desc(sum by (user) (slurm_user_cpus_running)))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPUs running per User",
   "type": "timeseries",
   "description": "CPUs running per user over time",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "slurm_user_cpus_running > 0", "legendFormat": "{{user}}" }
   ]
  },
  {
   "title": "SLURM Jobs",
   "type": "row",
   "description": "SLURM Jobs",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Jobs Queue",
   "type": "timeseries",
   "description": "Overview of the jobs queue over time",
   "gridPos": { "h": 16, "w": 11, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "slurm_queue_running != 0", "legendFormat": "running" },
    { "expr": "slurm_queue_pending != 0", "legendFormat": "pending" },
    { "expr": "slurm_queue_cancelled != 0", "legendFormat": "cancelled" },
    { "expr": "slurm_queue_failed != 0", "legendFormat": "failed" },
    { "expr": "slurm_queue_timeout != 0", "legendFormat": "timeout" },
    { "expr": "slurm_queue_suspended != 0", "legendFormat": "suspended" }
   ]
  },
  {
   "title": "Running Jobs per User",
   "type": "timeseries",
   "description": "Running Jobs per User",
   "gridPos": { "h": 8, "w": 6, "x": 11, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "slurm_user_jobs_running", "legendFormat": "{{user}}" }
   ]
  },
  {
   "title": "Pending Jobs per Users",
   "type": "timeseries",
   "description": "Pending Jobs per Users",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "slurm_user_jobs_pending != 0", "legendFormat": "{{user}}" }
   ]
  },
  {
   "title": "Running Jobs per Account",
   "type": "timeseries",
   "description": "Running Jobs per Account",
   "gridPos": { "h": 8, "w": 6, "x": 11, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "slurm_account_jobs_running", "legendFormat": "{{account}}" }
   ]
  },
  {
   "title": "Pending Jobs per Users",
   "type": "timeseries",
   "description": "Pending Jobs per Users",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "slurm_user_jobs_pending != 0", "legendFormat": "{{user}}" }
   ]
  },
  {
   "title": "SLURM Scheduler Details",
   "type": "row",
   "description": "SLURM Scheduler Details",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Slurm Scheduler Threads",
     "type": "stat",
     "description": "The number of current active slurmctld threads.",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "slurm_scheduler_threads", "legendFormat": "Slurm Scheduler Threads" }
     ]
    },
    {
     "title": "Agent Queue Size",
     "type": "stat",
     "description": "The agent mechanism helps to control communication between the Slrum daemons and the controller for a best effort.",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "slurm_scheduler_queue_size", "legendFormat": "Agent Queue Size" }
     ]
    },
    {
     "title": "DBD Agent Queue Length",
     "type": "gauge",
     "description": "DBD Agent Queue Length",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "slurm_scheduler_dbd_queue_size", "legendFormat": "DBD Agent Queue length" }
     ]
    }
   ]
  },
  {
   "title": "SLURM Scheduler Cycles",
   "type": "row",
   "description": "SLURM Scheduler Cycles",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Scheduler Cycles",
     "type": "timeseries",
     "description": "Scheduler Cycles",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      { "expr": "slurm_scheduler_last_cycle", "legendFormat": "Scheduler Last Cycle Time" },
      { "expr": "slurm_scheduler_mean_cycle", "legendFormat": "Scheduler Mean Cycle Time" }
     ]
    },
    {
     "title": "Backfill Scheduler Cycles",
     "type": "timeseries",
     "description": "Backfill Scheduler Cycles",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "slurm_scheduler_backfill_last_cycle",
       "legendFormat": "Scheduler Backfill Last Cycle"
      },
      {
       "expr": "slurm_scheduler_backfill_mean_cycle",
       "legendFormat": "Scheduler Backfill Mean Cycle"
      }
     ]
    },
    {
     "title": "Scheduler Backfill Depth Mean",
     "type": "timeseries",
     "description": "Scheduler Backfill Depth Mean",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "slurm_scheduler_backfill_depth_mean",
       "legendFormat": "Mean of processed jobs during backfilling scheduling cycles"
      }
     ]
    },
    {
     "title": "Total backfilled heterogeneous Job components",
     "type": "gauge",
     "description": "Number of heterogeneous job components started thanks to backfilling since last Slurm start",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "slurm_scheduler_backfilled_heterogeneous_total",
       "legendFormat": "Heterogeneous job components"
      }
     ]
    }
   ]
  },
  {
   "title": "Total Backfilled Jobs",
   "type": "row",
   "description": "Total Backfilled Jobs",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total Backfilled Jobs (since last slurm start)",
     "type": "timeseries",
     "description": "Number of jobs started thanks to backfilling since last Slurm start.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "delta(slurm_scheduler_backfilled_jobs_since_start_total[10m])",
       "legendFormat": "DELTA: Total number Backfilled Jobs (since last Slurm start)"
      },
      {
       "expr": "slurm_scheduler_backfilled_jobs_since_start_total",
       "legendFormat": "Total number Backfilled Jobs (since last Slurm start)"
      }
     ]
    },
    {
     "title": "Total Backfilled Jobs (since last stats cycle start)",
     "type": "timeseries",
     "description": "Number of jobs started thanks to backfilling since last time stats where reset",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "slurm_scheduler_backfilled_jobs_since_cycle_total",
       "legendFormat": " Total Backfilled Jobs (since last stats cycle start)"
      },
      {
       "expr": "delta(slurm_scheduler_backfilled_jobs_since_cycle_total[10m])",
       "legendFormat": "DELTA:  Total Backfilled Jobs (since last stats cycle start)"
      }
     ]
    }
   ]
  }
 ]
}