{
 "title": "Hardware",
 "tags": [
  "dashboard",
  "hw"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   { "name": "anarchy_group", "label": "Anarchy Group", "query": { "query": "label_values(up,anarchy_group)" } },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": {
     "query": "label_values(up{anarchy_group=~\"$anarchy_group\"},hostname)"
    }
   },
   {
    "name": "device_id",
    "label": "Device Class",
    "query": {
     "query": "label_values(lshw_device{anarchy_group=~\"$anarchy_group\", hostname=~\"$hostname\"},id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Devices",
   "type": "stat",
   "description": "Number of CPU devices in the selected nodes",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(lshw_device{anarchy_group=~\"$anarchy_group\", hostname=~\"$hostname\", id=~\"cpu(:)?[0-9]*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Banks",
   "type": "stat",
   "description": "Number of memory banks (DIMMs) in the selected nodes",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(lshw_device{anarchy_group=~\"$anarchy_group\", hostname=~\"$hostname\", id=~\"bank(:)?[0-9]*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Devices",
   "type": "stat",
   "description": "Number of disk devices in the selected nodes",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(lshw_device{anarchy_group=~\"$anarchy_group\", hostname=~\"$hostname\", id=~\"disk(:)?[0-9]*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Interfaces",
   "type": "stat",
   "description": "Number of network interfaces in the selected nodes",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(lshw_device{anarchy_group=~\"$anarchy_group\", hostname=~\"$hostname\", id=~\"network(:)?[0-9]*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Hardware Devices",
   "type": "stat",
   "description": "Total number of hardware devices in the selected nodes",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(lshw_device{anarchy_group=~\"$anarchy_group\", hostname=~\"$hostname\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Inventory",
   "type": "table",
   "description": "List of CPU devices in the selected nodes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "lshw_device{anarchy_group=~\"$anarchy_group\", hostname=~\"$hostname\", id=~\"cpu(:)?[0-9]*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Inventory",
   "type": "table",
   "description": "List of memory banks (DIMMs) in the selected nodes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "lshw_device{anarchy_group=~\"$anarchy_group\", hostname=~\"$hostname\", id=~\"bank(:)?[0-9]*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Inventory",
   "type": "table",
   "description": "List of disk devices in the selected nodes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "lshw_device{anarchy_group=~\"$anarchy_group\", hostname=~\"$hostname\", id=~\"disk(:)?[0-9]*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Inventory",
   "type": "table",
   "description": "List of network interfaces in the selected nodes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "lshw_device{anarchy_group=~\"$anarchy_group\", hostname=~\"$hostname\", id=~\"network(:)?[0-9]*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hardware Inventory (Raw)",
   "type": "table",
   "description": "List of individual hardware components in the selected nodes (raw view)",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "lshw_device{anarchy_group=~\"$anarchy_group\", hostname=~\"$hostname\", id=~\"$device_id(:)?[0-9]*\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}