{
 "title": "GPU",
 "description": "Nvidia GPU Metrics based on the prometheus metrics from github.com/utkuozdemir/nvidia_gpu_exporter",
 "tags": [
  "nvidia",
  "gpu",
  "system",
  "dashboard"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   { "name": "luna_group", "label": "Luna Group", "query": { "query": "label_values(up,luna_group)" } },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": {
     "query": "label_values(gpu_info{luna_group=~\"$luna_group\"},hostname)"
    }
   },
   { "name": "gpu", "label": "GPU", "query": { "query": "label_values(gpu_info,uuid)" } },
   {
    "name": "_gpu_host",
    "label": "_gpu_host",
    "query": {
     "query": "label_values(gpu_info{uuid=~\"$gpu\"},hostname)"
    }
   }
  ]
 },
 "panels": [
  { "title": "GPU [$gpu]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "gpu" },
  {
   "title": "Name",
   "type": "stat",
   "description": "The official product name of the GPU. This is an alphanumeric string. For all products.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gpu_info{uuid=\"$gpu\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "P-State",
   "type": "stat",
   "description": "The current performance state for the GPU. States range from P0 (maximum performance) to P12 (minimum performance).",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "prefix:P" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gpu_pstate{uuid=\"$gpu\"}"
    }
   ]
  },
  {
   "title": "GPU Utilization %",
   "type": "timeseries",
   "description": "Percent of time over the past sample period during which one or more kernels was executing on the GPU.\nThe sample period may be between 1 second and 1/6 second depending on the product.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "gpu_utilization_gpu_ratio{uuid=\"$gpu\"}"
    }
   ]
  },
  {
   "title": "Memory Utilization %",
   "type": "timeseries",
   "description": "Percent of time over the past sample period during which global (device) memory was being read or written.\nThe sample period may be between 1 second and 1/6 second depending on the product.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "gpu_utilization_memory_ratio{uuid=\"$gpu\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "description": "Core GPU temperature. in degrees C.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "gpu_temperature_gpu{uuid=\"$gpu\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Driver Version",
   "type": "stat",
   "description": "The version of the installed NVIDIA display driver. This is an alphanumeric string.",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gpu_info{uuid=\"$gpu\"}",
     "legendFormat": "{{driver_version}}"
    }
   ]
  },
  {
   "title": "Vbios Version",
   "type": "stat",
   "description": "The BIOS of the GPU board.",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gpu_info{uuid=\"$gpu\"}",
     "legendFormat": "{{vbios_version}}"
    }
   ]
  },
  {
   "title": "Throttle Reasons",
   "type": "bargauge",
   "description": "Information about factors that are reducing the frequency of clocks. If all throttle reasons are returned as \"Not Active\" it means that clocks are running as high as possible.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gpu_clocks_throttle_reasons_gpu_idle{uuid=\"$gpu\"}",
     "legendFormat": "Idle"
    },
    {
     "expr": "gpu_clocks_throttle_reasons_hw_thermal_slowdown{uuid=\"$gpu\"}",
     "legendFormat": "HW Thermal Slowdown"
    },
    {
     "expr": "gpu_clocks_throttle_reasons_sw_power_cap{uuid=\"$gpu\"}",
     "legendFormat": "SW Power Cap"
    },
    {
     "expr": "gpu_clocks_throttle_reasons_applications_clocks_setting{uuid=\"$gpu\"}",
     "legendFormat": "App Clocks Setting"
    },
    {
     "expr": "gpu_clocks_throttle_reasons_hw_power_brake_slowdown{uuid=\"$gpu\"}",
     "legendFormat": "HW Power Brake"
    },
    {
     "expr": "gpu_clocks_throttle_reasons_sw_thermal_slowdown{uuid=\"$gpu\"}",
     "legendFormat": "SW Thermal Slowdown"
    },
    {
     "expr": "gpu_clocks_throttle_reasons_sync_boost{uuid=\"$gpu\"}",
     "legendFormat": "Sync Boost"
    }
   ]
  },
  {
   "title": "GPU Clock Speed %",
   "type": "gauge",
   "description": "Current frequency of graphics (shader) clock\n/\nMaximum frequency of graphics (shader) clock.\n",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gpu_clocks_current_graphics_clock_hz{uuid=\"$gpu\"} / gpu_clocks_max_graphics_clock_hz{uuid=\"$gpu\"}"
    }
   ]
  },
  {
   "title": "Memory Clock Speed %",
   "type": "gauge",
   "description": "Current frequency of memory clock / Maximum frequency of memory clock",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gpu_clocks_current_memory_clock_hz{uuid=\"$gpu\"} / gpu_clocks_max_memory_clock_hz{uuid=\"$gpu\"}"
    }
   ]
  },
  {
   "title": "Fan Speed %",
   "type": "gauge",
   "description": "The fan speed value is the percent of the product's maximum noise tolerance fan speed that the device's fan is currently intended to run at. This value may exceed 100% in certain cases. Note: The reported speed is the intended fan speed. If the fan is physically blocked and unable to spin, this output will not match the actual fan speed. Many parts do not report fan speeds because they rely on cooling via fans in the surrounding enclosure.\n",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gpu_fan_speed_ratio{uuid=\"$gpu\"}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "description": "Core GPU temperature. in degrees C.",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gpu_temperature_gpu{uuid=\"$gpu\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Graphics Clock Speed",
   "type": "timeseries",
   "description": "Current frequency of graphics (shader) clock.",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "gpu_clocks_current_graphics_clock_hz{uuid=\"$gpu\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Video Clock Speed",
   "type": "timeseries",
   "description": "Current frequency of video encoder/decoder clock.",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "gpu_clocks_current_video_clock_hz{uuid=\"$gpu\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Power Draw",
   "type": "timeseries",
   "description": "The last measured power draw for the entire board, in watts. Only available if power management is supported. This reading is accurate to within +/- 5 watts",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "gpu_power_draw_watts{uuid=\"$gpu\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Power Draw %",
   "type": "gauge",
   "description": "The last measured power draw for the entire board, in watts. Only available if power management is supported. This reading is accurate to within +/- 5 watts / The software power limit in watts.",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gpu_power_draw_watts{uuid=\"$gpu\"} / gpu_power_default_limit_watts{uuid=\"$gpu\"}"
    }
   ]
  },
  {
   "title": "GPU Utilization %",
   "type": "gauge",
   "description": "Percent of time over the past sample period during which one or more kernels was executing on the GPU.\nThe sample period may be between 1 second and 1/6 second depending on the product.",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gpu_utilization_gpu_ratio{uuid=\"$gpu\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Memory Allocation %",
   "type": "gauge",
   "description": "Total memory allocated by active contexts / Total installed GPU memory.",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gpu_memory_used_bytes{uuid=\"$gpu\"} / gpu_memory_total_bytes{uuid=\"$gpu\"}"
    }
   ]
  },
  {
   "title": "Memory Utilization %",
   "type": "gauge",
   "description": "Percent of time over the past sample period during which global (device) memory was being read or written.\nThe sample period may be between 1 second and 1/6 second depending on the product.",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gpu_utilization_memory_ratio{uuid=\"$gpu\"}"
    }
   ]
  },
  {
   "title": "Memory Clock Speed",
   "type": "timeseries",
   "description": "Current frequency of memory clock.",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "gpu_clocks_current_memory_clock_hz{uuid=\"$gpu\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "SM Clock Speed",
   "type": "timeseries",
   "description": "Current frequency of SM (Streaming Multiprocessor) clock.",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "gpu_clocks_current_sm_clock_hz{uuid=\"$gpu\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  }
 ]
}