{
 "title": "Thermals and Power",
 "tags": [
  "thermals",
  "fans",
  "power",
  "dashboard"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   { "name": "luna_group", "label": "Luna group", "query": { "query": "label_values(up,luna_group)" } },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": {
     "query": "label_values(up{luna_group=~\"$luna_group\"},hostname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Power Status",
   "type": "stat",
   "description": "Machine power status",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ipmi_chassis_power_state{hostname=\"$hostname\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Available Sensors",
   "type": "stat",
   "description": "List of available sensor available on the target BMC ",
   "gridPos": { "h": 4, "w": 8, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ipmi_up{hostname=\"$hostname\"}",
     "legendFormat": "{{collector}}"
    }
   ]
  },
  {
   "title": "IPMI Sensors State",
   "type": "table",
   "description": "List of checks executed by BMC and their associated outcome.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "ipmi_sensor_state{hostname=\"$hostname\"}"
    }
   ]
  },
  {
   "title": "Machine Info",
   "type": "table",
   "description": "Manifacturer and Firmware info",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "ipmi_bmc_info{hostname=\"$hostname\"}"
    }
   ]
  },
  { "title": "Power", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "host_power" },
  {
   "title": "Power State",
   "type": "stat",
   "description": "Power faults check outcome",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ipmi_power_state{hostname=\"$hostname\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Power draw over time",
   "type": "timeseries",
   "description": "Overall chassis power draw reading over time, collected by the BMC ",
   "gridPos": { "h": 10, "w": 20, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "(sum(ipmi_dcmi_power_consumption_watts{hostname=\"$hostname\"}) - sum(nvidia_smi_power_draw_watts{hostname=\"$hostname\"})) \r\nOR \r\nsum(ipmi_dcmi_power_consumption_watts{hostname=\"$hostname\"})",
     "legendFormat": "system"
    },
    {
     "expr": "nvidia_smi_power_draw_watts{hostname=\"$hostname\"}",
     "legendFormat": "gpu"
    }
   ]
  },
  {
   "title": "Power draw",
   "type": "stat",
   "description": "Overall chassis power draw reading, collected by the BMC",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ipmi_dcmi_power_consumption_watts{hostname=\"$hostname\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Temperatures", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Temperatures",
   "type": "table",
   "description": "Temperatures of board components and related errors detected by BMC",
   "gridPos": { "h": 15, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ipmi_temperature_celsius{hostname=\"$hostname\", name=~\".*[tT][eE][mM]?[pP].*\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ipmi_temperature_state{hostname=\"$hostname\", name=~\".*[tT][eE][mM]?[pP].*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fan Speeds",
   "type": "table",
   "description": "Fan speed of board components and related errors detected by BMC",
   "gridPos": { "h": 15, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ipmi_fan_speed_rpm{hostname=\"$hostname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ipmi_fan_speed_state{hostname=\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Voltages",
   "type": "table",
   "description": "Voltages of board components and related errors  detected by BMC",
   "gridPos": { "h": 15, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ipmi_voltage_volts{hostname=\"$hostname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ipmi_voltage_state{hostname=\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Temperatures",
   "type": "table",
   "description": "Temperatures of GPUs",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "nvidia_smi_temperature_gpu{hostname=\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Fans",
   "type": "table",
   "description": "Fan speed of GPUs",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "nvidia_smi_fan_speed_ratio{hostname=\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}