---
- name: Install config_manager pip package
  ansible.builtin.pip:
    name: "{{ config_manager_noarch_pip_repository }}/config-manager/{{ config_manager_wheel }}"
    virtualenv: "{{ anarchy_local }}/python"
    extra_args: "--upgrade"

- name: Symlink '{{ anarchy_local }}/python/bin/trix-config-manager' to '{{ anarchy_local }}/sbin/trix-config-manager'
  ansible.builtin.file:
    src: "{{ anarchy_local }}/python/bin/trix-config-manager"
    dest: "{{ anarchy_local }}/sbin/trix-config-manager"
    state: link


# --- taken care off by config-slurm role
# Add the managed block to the managed files
#- name: Fix structure of managed files
#  include_tasks: managed_block.yml
#  loop: "{{ scripts_managed_files }}"
  
