---
slurm_conf_path: '/etc/slurm'
slurm_spool_path: '/var/spool/slurm'
slurm_log_path: '/var/log/slurm'

slurm_user_id: 891
slurm_group_id: 891

slurm_ctrl: 'controller1'
slurm_ctrl_list: 'controller1,controller2'

enable_slurm_pam: false

slurmdbd_sql_user: 'slurm_accounting'
slurmdbd_sql_db: 'slurm_accounting'

munge_user_id: 892
munge_group_id: 892
munge_conf_path: '/etc/munge'

# These flags are expected to be set by inventory/play:
# on_controller: true/false
# on_node: true/false
# in_image: true/false
# ha: true/false
