---
# Load OS-specific variables
- name: Load OS-specific vars
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "default.yml"

# Dispatch to OS-specific tasks
- name: Run OS-specific OpenHPC setup
  include_tasks: "{{ ansible_os_family }}.yml"

# Shared tasks across all OSes
- name: Install profile for modules
  template:
    src: z_modules.sh.j2
    dest: /etc/profile.d/z_modules.sh

- name: Install dummy module
  template:
    src: dummy-module.lua.j2
    dest: "{{ anarchy_modulefiles }}/dummy-module.lua"
  when:
    - on_controller
    - primary | default(True)
