---
# Enable SUSE HPC module (SLES only)
- name: Enable SUSE HPC module (SLES only)
  command: >
    SUSEConnect -p sle-module-HPC/{{ ansible_distribution_version }}/x86_64
  when: ansible_distribution in ["SUSE Linux Enterprise Server", "SLES"]

# Install environment modules (SUSE default)
- name: Install environment modules on SUSE
  community.general.zypper:
    name: "{{ envmodules_packages }}"
    state: present
  when: not (openhpc_manages_modules | default(false))
