---
# Generic defaults (lowest precedence)

# Safe fallback for all OSes
envmodules_packages:
  - environment-modules

envmodules_files_path: '{{ anarchy_shared }}/modulefiles'

envmodules_default_list: []
envmodules_list: '{{ envmodules_default_list + additional_env_modules|default([]) }}'

envmodules_skiproot: true
