#!/bin/bash

function add_message() {
  echo -e "$1" | fold -w70 -s >> /tmp/mesg.$$.dat
}

function show_message() {
  echo "+---------------------------------- X -------------------------------------+"
  echo "|                                                                          |"
  while read -r LINE
  do
    printf '|  %-70s  |\n' "$LINE"
  done < /tmp/mesg.$$.dat
  echo "|                                                                          |"
  echo "+--------------------------------------------------------------------------+"
  truncate -s0 /tmp/mesg.$$.dat
}

function count_down() {
  tel=$1
  while [ "$tel" -gt "0" ]; do
    echo -n "[$tel]  "
    sleep 1
    printf "\r"
    tel=$[tel-1]
  done
  echo
}

# not as root
if [[ $EUID -eq 0 ]]; then
  echo "Run as a regular user with sudo, not root."
  exit 1
fi

echo
add_message "Welcome to AnarchyHPC"
add_message "The system will now be prepared first..."
show_message
count_down 5
bash prepare.sh
PREP_RET=$?

if [ "$PREP_RET" != "0" ]; then
    add_message "prepare.sh failed with exit code $PREP_RET."
    add_message "Installation cannot continue."
    show_message
    exit 1
fi

cd site

if [ ! -f tui_configurator ]; then
    add_message "tui_configurator is missing. Please ensure it exists in site/."
    show_message
    exit 1
fi

# Automatically fix permissions
if [ ! -x tui_configurator ]; then
    chmod 755 tui_configurator
fi

./tui_configurator
TUI_RET=$?

if [ "$TUI_RET" != "0" ]; then
    add_message "The configuration TUI exited with an error."
    add_message "Please correct the problem and try again."
    show_message
    exit 1
fi

# The TUI now writes directly to group_vars/all.yml and hosts.
# Do NOT overwrite them with example files.

# hosts file is already generated by tui_configurator
# do NOT overwrite it

./ssh_bootstrap.sh

echo
add_message "Ansible Playbooks will now run"
show_message
count_down 5
ansible-playbook controller.yml compute-default.yml compute-ubuntu.yml
