---

- name: reload firewalld
  service:
    name: firewalld
    state: reloaded

- name: reload network backend
  service:
    name: "{{ firewalld_network_backend }}"
    state: restarted
  listen: reload firewalld
  when: firewalld_network_backend == 'NetworkManager'

- name: fix firewall zones
  shell: /tmp/fix-firewalld-zones.sh
  ignore_errors: true
  listen: reload firewalld

