---

- name: Verify if /etc/hosts exists
  stat:
    path: /etc/hosts
  register: etc_hosts

- name: Create empty /etc/hosts
  file:
    path: /etc/hosts
    state: touch
  when: not etc_hosts.stat.exists

- block:
  - name: Set HA controllers' domain name
    blockinfile:
      path: /etc/hosts
      block: |
        {{anarchy_ctrl1_ip}}    {{anarchy_ctrl1_hostname}}.{{anarchy_domain}} {{anarchy_ctrl1_hostname}}
        {{anarchy_ctrl2_ip}}    {{anarchy_ctrl2_hostname}}.{{anarchy_domain}} {{anarchy_ctrl2_hostname}}
        {{anarchy_ctrl3_ip}}    {{anarchy_ctrl3_hostname}}.{{anarchy_domain}} {{anarchy_ctrl3_hostname}}
        {{anarchy_ctrl4_ip}}    {{anarchy_ctrl4_hostname}}.{{anarchy_domain}} {{anarchy_ctrl4_hostname}}
        {{anarchy_ctrl_ip}}    {{anarchy_ctrl_hostname}}.{{anarchy_domain}} {{anarchy_ctrl_hostname}}
    when: 
      - anarchy_ctrl3_ip is defined
      - anarchy_ctrl3_hostname is defined
      - anarchy_ctrl4_ip is defined
      - anarchy_ctrl4_hostname is defined

  - name: Set HA controllers' domain name
    blockinfile:
      path: /etc/hosts
      block: |
        {{anarchy_ctrl1_ip}}    {{anarchy_ctrl1_hostname}}.{{anarchy_domain}} {{anarchy_ctrl1_hostname}}
        {{anarchy_ctrl2_ip}}    {{anarchy_ctrl2_hostname}}.{{anarchy_domain}} {{anarchy_ctrl2_hostname}}
        {{anarchy_ctrl3_ip}}    {{anarchy_ctrl3_hostname}}.{{anarchy_domain}} {{anarchy_ctrl3_hostname}}
        {{anarchy_ctrl_ip}}    {{anarchy_ctrl_hostname}}.{{anarchy_domain}} {{anarchy_ctrl_hostname}}
    when: 
      - anarchy_ctrl3_ip is defined
      - anarchy_ctrl3_hostname is defined
      - (anarchy_ctrl4_ip is not defined) or (anarchy_ctrl4_hostname is not defined)

  - name: Set HA controllers' domain name
    blockinfile:
      path: /etc/hosts
      block: |
        {{anarchy_ctrl1_ip}}    {{anarchy_ctrl1_hostname}}.{{anarchy_domain}} {{anarchy_ctrl1_hostname}}
        {{anarchy_ctrl2_ip}}    {{anarchy_ctrl2_hostname}}.{{anarchy_domain}} {{anarchy_ctrl2_hostname}}
        {{anarchy_ctrl_ip}}    {{anarchy_ctrl_hostname}}.{{anarchy_domain}} {{anarchy_ctrl_hostname}}
    when: 
      - (anarchy_ctrl3_ip is not defined) or (anarchy_ctrl3_hostname is not defined)
      - (anarchy_ctrl4_ip is not defined) or (anarchy_ctrl4_hostname is not defined)
  when: ha|default(False)

- name: Set non-HA controller's domain name
  blockinfile:
    path: /etc/hosts
    block: |
      {{anarchy_ctrl_ip}}    {{anarchy_ctrl_hostname}}.{{anarchy_domain}} {{anarchy_ctrl_hostname}}
  when: not ha|default(False)

# Needs dnspython module. Available in RL,Alma,RH,C9, but not in 8. commented out for now. -Antoine
#- name: Verify if i can resolve anarchy_anarchy_external_fqdn
#  set_fact:
#    anarchy_anarchy_external_fqdn_resolvable: "{{ query('community.general.dig', anarchy_anarchy_external_fqdn, '@'+anarchy_dns_forwarders|first) }}"
#
#- name: anarchy_anarchy_external_fqdn warning
#  fail:
#    msg: "{{ anarchy_anarchy_external_fqdn }} is not resolvable! Please add an entry for {{ anarchy_anarchy_external_fqdn }} to /etc/hosts"
#  ignore_errors: true
#  when:
#    - anarchy_anarchy_external_fqdn_resolvable is iterable
#    - '"NXDOMAIN" is in anarchy_anarchy_external_fqdn_resolvable'

- name: Re-gather facts
  action: setup
