---
###############################################################################
# 1. Load OS‑specific tunables vars
###############################################################################

- name: Load OS‑specific tunables vars
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yaml"
    - "{{ ansible_os_family }}{{ ansible_distribution_major_version }}.yaml"
    - "{{ ansible_os_family }}.yaml"        # RedHat.yaml, Suse.yaml, Debian.yaml
    - "default.yaml"
  no_log: false

###############################################################################
# 2. Dispatch to OS‑specific tasks
###############################################################################

- name: Run SUSE tunables
  include_tasks: Suse.yml
  when: ansible_os_family == "Suse"

- name: Run RedHat tunables
  include_tasks: RedHat.yml
  when: ansible_os_family == "RedHat"

- name: Run Debian/Ubuntu tunables
  include_tasks: Debian.yml
  when: ansible_os_family == "Debian"
