---
- hosts: localhost
  pre_tasks:
    - name: Set image name
      set_fact:
        image_name: "alma-image"
      tags: always

- import_playbook: imports/anarchy-redhat-image-create.yml
  vars:
    image_name: "{{ hostvars['localhost']['image_name'] }}"
    image_password:
    alternative_distribution: almalinux:latest
    alternative_image_source: 'docker'
    alternative_image_distr: 'almalinux'

- import_playbook: imports/anarchy-redhat-image-setup.yml
  vars:
    hostlist: "{{ hostvars['localhost']['image_name'] }}.osimages.xcat"

- hosts:
    - "{{ hostvars['localhost']['image_name'] }}.osimages.xcat"
  roles:
    - role: anarchy/slurm
      slurm_conf_path: '{{ anarchy_shared }}/etc/slurm'
      slurm_spool_path: '{{ anarchy_shared }}/var/spool/slurm'
      munge_conf_path: '{{ anarchy_shared }}/etc/munge'
      tags: slurm

- hosts: controllers
  roles:
    - role: anarchy/osimage-pack   # NEW ROLE replacing luna/osimage-pack
      vars:
        image_name: "{{ hostvars['localhost']['image_name'] }}"
      tags: pack-images
