---
- hosts: localhost
  pre_tasks:
    - name: Set image name
      set_fact:
        image_name: "opensuse-image"
      tags: always

- import_playbook: imports/anarchy-opensuse-image-create.yml
  vars:
    image_name: "{{ hostvars['localhost']['image_name'] }}"
    image_password:
    opensuse_release: "16.0"

- import_playbook: imports/anarchy-opensuse-image-setup.yml
  vars:
    hostlist: "{{ hostvars['localhost']['image_name'] }}.osimages.xcat"

- hosts:
    - "{{ hostvars['localhost']['image_name'] }}.osimages.xcat"
  roles: []

- hosts: controllers
  roles:
    - role: anarchy/osimage-pack
      vars:
        image_name: "{{ hostvars['localhost']['image_name'] }}"
      tags: pack-images
