---
# Default values for Obol

# Fallback — overridden by OS-specific vars
obol_packages: []

users_home_path: '/home'
obol_conf_path: '/etc/obol'
ldap_host: "{{ inventory_hostname }}"

obol_use_ds389: false
