---
tunables_packages:
  - tuned
  - tuned-utils
  - tuned-gtk
  - tuned-profiles-atomic
  - tuned-profiles-nfv
  - tuned-profiles-oracle
  - tuned-profiles-realtime
  - tuned-utils-systemtap
  - sysstat
  - lvm2

# SUSE does NOT ship 'hpc-compute'
# Best SUSE equivalent for compute nodes is 'latency-performance'
compute_tuned_profile: "latency-performance"

# This one *is* available on SUSE and appropriate for controllers
controller_tuned_profile: "throughput-performance"
