---
tunables_packages:
  - tuned
  - tuned-utils
  - tuned-profiles-cpu-partitioning
  - tuned-profiles-compat
  - tuned-profiles-sap
  - tuned-profiles-virtual-host
  - tuned-profiles-virtual-guest
  - sysstat
  - numactl
  - lvm2
  - ethtool

compute_tuned_profile: "hpc-compute"
controller_tuned_profile: "throughput-performance"
