---
# Install config_blocks pip package inside the shared virtualenv
- name: Install config_blocks pip package
  ansible.builtin.pip:
    name: "{{ config_slurm_noarch_pip_repository }}/config-blocks/{{ config_blocks_wheel }}"
    virtualenv: "{{ anarchy_local }}/python"
    extra_args: "--upgrade"

# Install config_slurm pip package inside the shared virtualenv
- name: Install config_slurm pip package
  ansible.builtin.pip:
    name: "{{ config_slurm_noarch_pip_repository }}/config-slurm/{{ config_slurm_wheel }}"
    virtualenv: "{{ anarchy_local }}/python"
    extra_args: "--upgrade"

# Symlink '{{ anarchy_local }}/python/bin/config-slurm' to '{{ anarchy_local }}/sbin/config-slurm'
- name: Symlink '{{ anarchy_local }}/python/bin/config-slurm' to '{{ anarchy_local }}/sbin/config-slurm'
  ansible.builtin.file:
    src: "{{ anarchy_local }}/python/bin/config-slurm"
    dest: "{{ anarchy_local }}/sbin/config-slurm"
    state: link

# Add the managed block to the managed files
- name: Fix structure of managed files
  include_tasks: managed_block.yml
  loop: "{{ scripts_managed_files }}"
