---
- block:
  - name: Clean package manager caches (RedHat)
    command: yum clean all
    when: ansible_facts['os_family'] == "RedHat"

  - name: Clean package manager caches (Debian)
    command: apt-get clean
    when: ansible_facts['os_family'] == "Debian"

  - name: Cleanup /tmp
    command: rm -f /tmp/*

  when: in_image
  tags: always
