---
- name: Load OS‑specific OpenLDAP vars
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yaml"
    - "{{ ansible_os_family }}{{ ansible_distribution_major_version }}.yaml"
    - "{{ ansible_os_family }}.yaml"
    - "default.yaml"

- name: Run OpenLDAP stack for RedHat
  include_tasks: RedHat.yml
  when: ansible_os_family == "RedHat"

- name: Run OpenLDAP stack for SUSE
  include_tasks: Suse.yml
  when: ansible_os_family == "Suse"

- name: Run OpenLDAP stack for Debian/Ubuntu
  include_tasks: Debian.yml
  when: ansible_os_family == "Debian"
