---
- debug:
    msg: "{{ openldap_server_dir_path }}"

###############################################################################
# RedHat: Install dependencies
###############################################################################

- name: Install dependencies (RedHat)
  yum:
    name: python3-policycoreutils
    state: installed
  tags: install-only
  retries: "{{ rpm_retries | default(3) }}"
  delay: "{{ rpm_delay | default(15) }}"

###############################################################################
# PACKAGE INSTALLATION
###############################################################################

- name: Install OpenLDAP packages (RedHat)
  yum:
    name: "{{ openldap_packages }}"
    state: present
    enablerepo:
      - plus
      - powertools
  tags: install-only
  retries: "{{ rpm_retries | default(3) }}"
  delay: "{{ rpm_delay | default(15) }}"

- name: Determine openldap version
  shell: "rpm -q openldap-servers | grep -oE '[0-9]\\.[0-9]' | tr -d '.' | head -n1"
  register: openldap_version

- debug:
    msg: "OpenLDAP release {{ openldap_version.stdout }}"
  when: openldap_version is defined

###############################################################################
# SELINUX
###############################################################################

- block:
    - name: Selinux fcontext on files
      sefcontext:
        target: "{{ openldap_server_conf_path }}(/.*)?"
        setype: slapd_db_t
  when: ansible_selinux.status == "enabled"

###############################################################################
# CLUSTER CA HANDLING (shared include)
###############################################################################

#- include_tasks: ca.yml

###############################################################################
# TLS + DEFAULTS (RedHat)
###############################################################################

- name: Hash OpenLDAP root password
  command: slappasswd -h {SSHA} -s {{ ldap_root_password }}
  register: ldap_root_password_hash
  changed_when: false
  when: primary | default(true)

- name: Adjust OpenLDAP server TLS configuration
  lineinfile:
    create: true
    path: "{{ openldap_server_defaults_file }}"
    regexp: '^SLAPD_URLS='
    line: 'SLAPD_URLS="{{ openldap_endpoints }}"'

- name: Adjust OpenLDAP client TLS configuration (RedHat)
  lineinfile:
    path: /etc/openldap/ldap.conf
    regexp: '^TLS_CACERT'
    line: 'TLS_CACERT   /etc/pki/tls/certs/ca-bundle.crt'

###############################################################################
# SLAPD.D RELOCATION
###############################################################################

- name: Get /etc/openldap/slapd.d status
  stat:
    path: /etc/openldap/slapd.d
  register: default_openldap_path

- block:
    - name: Ensure OpenLDAP configuration directory exists
      file:
        path: "{{ openldap_server_conf_path }}"
        state: directory
        owner: "{{ openldap_default_user }}"
        group: "{{ openldap_default_group }}"
        setype: slapd_db_t
        seuser: system_u
      when: primary | default(false)

    - name: Copy default configuration to {{ openldap_server_conf_path }}
      shell: rsync -raW -AX /etc/openldap/slapd.d/* {{ openldap_server_conf_path | quote }}
      args:
        creates: "{{ openldap_server_conf_path }}/cn=config.ldif"
      register: openldap_copy
      ignore_errors: true
      when: primary | default(true)

    - name: Copy default configuration without xattr
      shell: rsync -raW /etc/openldap/slapd.d/* {{ openldap_server_conf_path | quote }}
      args:
        creates: "{{ openldap_server_conf_path }}/cn=config.ldif"
      when:
        - primary | default(true)
        - openldap_copy is failed

    - name: Delete default configuration
      file:
        path: /etc/openldap/slapd.d
        state: absent

    - name: Replace default configuration path with symlink
      file:
        src: "{{ openldap_server_conf_path }}"
        dest: /etc/openldap/slapd.d
        state: link
        force: true
  when:
    openldap_server_conf_path | string not in '/etc/openldap/slapd.d'
    and default_openldap_path.stat.isdir

###############################################################################
# DESTROY EXISTING DB IF REQUESTED
###############################################################################

- block:
    - name: Verifying for data existence
      stat:
        path: "{{ openldap_server_dir_path }}"
      register: openldap_server_dir_stat

    - block:
        - name: Verifying previous data backup existence
          stat:
            path: "{{ openldap_server_dir_path }}.backup"
          register: openldap_server_dir_path_backup

        - name: Deleting previous data backup
          file:
            path: "{{ openldap_server_dir_path }}.backup"
            state: absent
          when:
            - openldap_server_dir_path_backup.stat.isdir is defined
            - openldap_server_dir_path_backup.stat.isdir

        - name: Stop OpenLDAP service
          systemd:
            name: slapd
            state: stopped

        - name: Moving current data to backup
          command: "mv -f {{ openldap_server_dir_path }} {{ openldap_server_dir_path }}.backup"
      when: openldap_server_dir_stat.stat.exists
  when:
    - override | default(false)
    - primary | default(true)

###############################################################################
# NON‑HA ENABLE
###############################################################################

- name: Enable OpenLDAP service (non‑HA)
  systemd:
    name: slapd
    enabled: true
  when: not ha | default(false)

###############################################################################
# INITIAL DATA + SCHEMAS (PRIMARY)
###############################################################################

- block:
    - name: Ensure OpenLDAP data directory exists
      file:
        path: "{{ openldap_server_dir_path }}"
        state: directory
        owner: "{{ openldap_default_user }}"
        group: "{{ openldap_default_group }}"
        setype: slapd_db_t
        seuser: system_u

    - name: Start OpenLDAP service
      systemd:
        name: slapd
        state: started
        enabled: true

    - name: Copy OpenLDAP schemas
      copy:
        src: "{{ item }}"
        dest: /etc/openldap/schema/
        owner: "{{ openldap_default_user }}"
        group: "{{ openldap_default_group }}"
        mode: "0644"
      loop:
        - rfc2307bis.ldif
        - autoinc.ldif
        - local_schema.ldif
  when: primary | default(true)

###############################################################################
# OPENLDAP <= 2.4
###############################################################################

- block:
    - name: Load OpenLDAP schemas (<= 2.4)
      command: ldapadd -c -Y EXTERNAL -H ldapi:/// -Q -f /etc/openldap/schema/{{ item }}.ldif
      args:
        creates: "/etc/openldap/slapd.d/cn=config/cn=schema/cn={?}{{ item }}.ldif"
      loop:
        - cosine
        - inetorgperson
        - rfc2307bis
        - autoinc
        - ppolicy

    - name: Render OpenLDAP configuration (<= 2.4)
      template:
        src: "{{ item }}.j2"
        dest: "/tmp/{{ item }}"
      loop:
        - config.ldif
        - local.ldif
        - proxy.ldif
      changed_when: false

    - name: Copy OpenLDAP overlay configurations (<= 2.4)
      copy:
        src: "{{ item }}"
        dest: /tmp/
      loop:
        - ppolicy.ldif
        - memberof.ldif

    - name: Load OpenLDAP global configuration (<= 2.4)
      command: ldapmodify -c -Y EXTERNAL -H ldapi:/// -Q -f /tmp/config.ldif
      args:
        creates: "/etc/openldap/slapd.d/cn=config.ldif"
      notify: restart openldap
      when:
        - primary | default(true)

    - name: Load OpenLDAP local configuration (<= 2.4)
      command: ldapmodify -c -Y EXTERNAL -H ldapi:/// -Q -f /tmp/{{ item }}
      args:
        creates: "/etc/openldap/slapd.d/cn=config/olcDatabase={?}hdb/olcOverlay={0}memberof.ldif"
      loop:
        - config.ldif
        - local.ldif
        - proxy.ldif
        - ppolicy.ldif
        - memberof.ldif
      notify: restart openldap

    - name: Check local schemas
      command: 'ldapsearch -H ldapi:// -Y EXTERNAL -b "dc=local" "cn=pwdDefaultPolicy,ou=Policies,dc=local"'
      register: ldapsearch
      failed_when: false
      changed_when: false

    - name: Load OpenLDAP local schema
      command: >
        ldapadd -x -H ldapi:// -D "cn=manager,dc=local" -w {{ ldap_root_password }}
                                 -f /etc/openldap/schema/local_schema.ldif
      ignore_errors: true
      when: ldapsearch.rc == 32
  when:
    - primary | default(true)
    - openldap_version is defined
    - openldap_version.stdout | int < 25

###############################################################################
# OPENLDAP 2.5+
###############################################################################

- block:
    - name: Load OpenLDAP schemas (2.5+)
      command: ldapadd -c -Y EXTERNAL -H ldapi:/// -Q -f /etc/openldap/schema/{{ item }}.ldif
      args:
        creates: "/etc/openldap/slapd.d/cn=config/cn=schema/cn={?}{{ item }}.ldif"
      loop:
        - cosine
        - inetorgperson
        - rfc2307bis
        - autoinc

    - name: Render OpenLDAP configuration (2.5+)
      template:
        src: "{{ item }}-25.j2"
        dest: "/tmp/{{ item }}"
      loop:
        - config.ldif
        - local.ldif
        - proxy.ldif
      changed_when: false

    - name: Copy OpenLDAP overlay configurations (2.5+)
      copy:
        src: "{{ item }}"
        dest: "/tmp/{{ item.split('-') | first }}"
      loop:
        - memberof.ldif-25

    - name: Load OpenLDAP global configuration (2.5+)
      command: ldapmodify -c -Y EXTERNAL -H ldapi:/// -Q -f /tmp/config.ldif
      args:
        creates: "/etc/openldap/slapd.d/cn=config.ldif"
      notify: restart openldap

    - name: Load OpenLDAP local configuration (2.5+)
      command: ldapmodify -c -Y EXTERNAL -H ldapi:/// -Q -f /tmp/{{ item }}
      args:
        creates: "/etc/openldap/slapd.d/cn=config/olcDatabase={?}mdb/olcOverlay={0}memberof.ldif"
      loop:
        - config.ldif
        - local.ldif
        - proxy.ldif
        - memberof.ldif
      notify: restart openldap

    - name: Load slapcat data
      command: "slapcat -n 0"
      register: slapcat_data

    - block:
        - name: Load ppolicy module
          command: "ldapadd -Y EXTERNAL -H ldapi:/// -f {{ role_path }}/files/ppolicyload.ldif"

        - name: Load ppolicy overlay
          command: "ldapadd -Y EXTERNAL -H ldapi:/// -f {{ role_path }}/files/ppolicyoverlay.ldif"
      when: "'ppolicy' not in slapcat_data.stdout"
      ignore_errors: true

    - name: Check local schemas
      command: 'ldapsearch -H ldapi:// -Y EXTERNAL -b "dc=local" "cn=pwdDefaultPolicy,ou=Policies,dc=local"'
      register: ldapsearch
      failed_when: false
      changed_when: false

    - name: Load OpenLDAP local schema
      command: >
        ldapadd -x -H ldapi:// -D "cn=manager,dc=local" -w {{ ldap_root_password }}
                                 -f /etc/openldap/schema/local_schema.ldif
      ignore_errors: true
      when: ldapsearch.rc == 32
  when:
    - primary | default(true)
    - openldap_version is defined
    - openldap_version.stdout | int > 24

###############################################################################
# HA INTEGRATION
###############################################################################

- block:
    - name: Disable OpenLDAP service for H/A
      systemd:
        name: slapd
        state: "{{ 'started' if primary else 'stopped' }}"
        enabled: false

    - name: Add pacemaker resource
      pcs_resource:
        name: openldap
        resource_class: systemd
        resource_type: systemd:slapd
        options: "meta migration-threshold=3 failure-timeout=120s op monitor interval=30 --group Anarchy-stack"
        state: present
      when: primary | default(true)
  when: ha | default(false)
  tags: pcs

- meta: flush_handlers
