---
# No vendor-specific packages
config_genders_noarch_pip_repository: ""
config_genders_wheel: ""
config_blocks_wheel: ""

scripts_managed_files:
  - /etc/genders

scripts_managed_block_comment1: "# Managed block start."
scripts_managed_block_comment2: "# Remove the managed block to override manually."
scripts_managed_block_start_delimiter: "#### Managed block start ####"
scripts_managed_block_end_delimiter:   "#### Managed block end   ####"
scripts_managed_block_start_regex:     "#### Managed block start ####"
scripts_managed_block_end_regex:       "#### Managed block end   ####"

cg_admin_group: 'admins'
