---
# Base directory for cluster-local data
shared_root: '/opt/cluster'

# Directory definitions used by other roles
shared_tree_dirs:
  - name: 
    path: '{{ anarchy_root }}'
  - name: anarchy_sync
    path: '{{ anarchy_root }}/sync'
  - name: anarchy_data
    path: '{{ anarchy_root }}/data'
  - name: anarchy_etc
    path: '{{ anarchy_root }}/etc'
  - name: anarchy_sbin
    path: '{{ anarchy_root }}/sbin'
  - name: anarchy_ondemand
    path: '{{ anarchy_root }}/ondemand'
  - name: anarchy_ssl
    path: '{{ anarchy_root }}/etc/ssl'
