---
- name: Include password tasks
  include_role:
    name: anarchy/password

- name: Include ssh tasks
  include_role:
    name: anarchy/ssh
  vars:
    extend_image: true

- name: Add dracut.conf.d entries
  template:
    src: anarchy.conf.j2
    dest: "{{ image_path }}/etc/dracut.conf.d/anarchy.conf"

- name: Configuring resolv.conf
  copy:
    dest: "{{ image_path }}/etc/resolv.conf"
    content: "nameserver {{ trix_ctrl_ip }}"
