---
- name: Load OS‑specific variables
  include_vars: "{{ package_arch }}/docker-{{ image_create_distribution }}.yaml"
  no_log: true
  ignore_errors: true

- name: Create /dev
  file:
    path: /dev/
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Create basic /dev files
  command: "/usr/bin/mknod /dev/{{ item.dev }} {{ item.t }} {{ item.ma }} {{ item.mi }}"
  args:
    creates: "/dev/{{ item.dev }}"
  with_items:
    - {dev: "null",   mo: "666", t: 'c', ma: 1, mi: 3}
    - {dev: "zero",   mo: "666", t: 'c', ma: 1, mi: 5}
    - {dev: "random", mo: "666", t: 'c', ma: 1, mi: 8}
    - {dev: "urandom",mo: "666", t: 'c', ma: 1, mi: 9}
    - {dev: "console",mo: "600", t: 'c', ma: 5, mi: 1}
    - {dev: "ptmx",   mo: "666", t: 'c', ma: 5, mi: 2}
    - {dev: "tty",    mo: "666", t: 'c', ma: 5, mi: 0}

- name: Ensure /dev/null is world writeable
  file:
    path: /dev/null
    mode: "0666"

- name: Updating Apt
  shell: "apt-get update"
  ignore_errors: true
  when: image_update_packages | default(True)

- name: Install core packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  ignore_errors: true
  with_items: "{{ image_core_packages }}"
  retries: "{{ rpm_retries | default(3) }}"
  delay: "{{ rpm_delay | default(15) }}"
