---
- name: Include password tasks
  include_role:
    name: anarchy/password

- name: Include ssh tasks
  include_role:
    name: anarchy/ssh
  vars:
    extend_image: true

- name: Add initramfs-tools configuration
  template:
    src: anarchy-initramfs.conf.j2
    dest: "{{ image_path }}/etc/initramfs-tools/conf.d/anarchy.conf"

- name: Configuring resolv.conf
  copy:
    dest: "{{ image_path }}/etc/resolv.conf"
    content: "nameserver {{ anarchy_ctrl_ip }}"
