---
- name: Include password tasks
  include_role:
    name: anarchy/password

- name: Include ssh tasks
  include_role:
    name: anarchy/ssh
  vars:
    extend_image: true

- name: Configuring resolv.conf
  copy:
    dest: "{{ image_path }}/etc/resolv.conf"
    content: "nameserver {{ anarchy_ctrl_ip }}"
