---
- name: Load OS‑specific variables
  include_vars: "{{ package_arch }}/image-{{ image_create_distribution }}.yaml"
  no_log: false
  ignore_errors: true

# ---------------------------------------------------------
# Configure AnarchyHPC repos (Ubuntu style)
# ---------------------------------------------------------
- name: Write AnarchyHPC repo files
  template:
    src: ubuntu-repo.j2
    dest: "/etc/apt/sources.list.d/{{ item.name }}.list"
  loop: "{{ anarchyhpc_repositories }}"
  when: item.name is defined
  tags: repos

# ---------------------------------------------------------
# Prepare apt
# ---------------------------------------------------------
- name: Update apt cache
  command: "apt-get update"

# ---------------------------------------------------------
# Install core packages
# ---------------------------------------------------------
- name: Install core packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: false
  loop: "{{ image_core_packages }}"
  retries: "{{ rpm_retries | default(3) }}"
  delay: "{{ rpm_delay | default(15) }}"

# ---------------------------------------------------------
# Enable services
# ---------------------------------------------------------
- name: Enabling services
  service:
    name: "{{ item }}"
    enabled: true
  loop:
    - network-manager
    - ssh
  ignore_errors: true
