---
- name: Load OS‑specific variables
  include_vars: "{{ package_arch }}/image-{{ image_create_distribution }}.yaml"
  no_log: true
  ignore_errors: true

- name: Configure repos
  lineinfile:
    path: /etc/apt/sources.list
    line: "deb http://archive.ubuntu.com/ubuntu {{ ubuntu_distribution_release }} main universe"
    state: present
    create: yes

- name: Updating Apt
  shell: "apt-get update"
  ignore_errors: true
  when: image_update_packages | default(True)

- name: Install core packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ image_core_packages }}"
  retries: "{{ rpm_retries | default(3) }}"
  delay: "{{ rpm_delay | default(15) }}"

- name: Disable tinysshd if it is there
  service:
    name: "{{ item }}"
    enabled: false
  ignore_errors: true
