---
- name: Check if Terraform is installed
  ansible.builtin.command: terraform -version
  register: terraform_check
  ignore_errors: true

- block:
    - name: Install yum-utils
      ansible.builtin.package:
        name: yum-utils
        state: present

    - name: Add HashiCorp repo
      ansible.builtin.command: >
        yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
      args:
        creates: /etc/yum.repos.d/hashicorp.repo

    - name: Install Terraform
      ansible.builtin.package:
        name: terraform
        state: present
  when: terraform_check.rc != 0
