---
- name: Check if Terraform is installed
  command: terraform -version
  register: terraform_check
  ignore_errors: true

- block:
    - name: Install yum-utils
      yum:
        name: yum-utils
        state: present

    - name: Add HashiCorp repo
      command: yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo

    - name: Install Terraform
      yum:
        name: terraform
        state: present
  when: terraform_check.rc != 0
