---
# tasks file for slurm

- name: Load OS-specific Slurm vars
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"
    - "{{ ansible_distribution }}.yml"
  tags: always

- name: Ensure munge and slurm users/groups exist
  include_tasks: users.yml

- name: Install Slurm stack
  include_tasks: install.yml

- name: Ensure Slurm paths and symlinks
  include_tasks: paths.yml

- name: Configure munge
  include_tasks: munge.yml

- name: Configure Slurm config files
  include_tasks: config.yml

- name: Configure systemd overrides
  include_tasks: systemd.yml

- name: Configure Slurm controller
  include_tasks: controller.yml
  when: on_controller | default(false)

- name: Configure Slurm compute node
  include_tasks: compute.yml
  when: on_node | default(false)

- name: Configure HA resources
  include_tasks: ha.yml
  when: ha | default(false)
