---
prometheus_amd_exporter_version: "v2.0.0"   # must match a real tag

prometheus_amd_exporter_git_repo: "https://github.com/amd/amd_smi_exporter.git"
prometheus_amd_exporter_git_version: "{{ prometheus_amd_exporter_version }}"

prometheus_amd_exporter_web_listen_port: "14209"
prometheus_amd_exporter_web_listen_host: "0.0.0.0"

prometheus_amd_exporter_log_dir: "/var/log/prometheus"
prometheus_amd_exporter_binary_install_dir: "/usr/local/bin"

prometheus_amd_exporter_system_user: "prometheus-amd-exporter"
prometheus_amd_exporter_system_group: "prometheus"
prometheus_amd_exporter_additional_system_groups: []

prometheus_amd_exporter_packages:
  - golang
  - make
  - rocm-smi
