---
# Ensure facts are gathered
- hosts: controllers, localhost
  tasks:
    - debug:
        msg: "Initializing all involved hosts"
  tags: always


- hosts: controllers
  pre_tasks:
    - fail:
        msg: "This playbook should only be run on the active controller"
      when:
        - ha | default(false)
        - not primary | default(false)

    - name: Validate image name
      set_fact:
        regex_image_name: "{{ image_name | regex_search('^[a-zA-Z0-9\\ \\-\\_\\.]+$') }}"

    - fail:
        msg: "Image name {{ image_name }} is not compliant."
      when: regex_image_name != image_name

    - name: Determine controller distribution
      set_fact:
        controller_distribution: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}"

    - name: Determine if base image must be downloaded
      set_fact:
        download_base_image: true
        image_create_minimal: false
      when:
        - alternative_distribution is defined
        - alternative_distribution != controller_distribution
        - alternative_image_source is defined
        - alternative_image_source != 'osgrab'

  roles:
    - role: lock-check
      tags: always

    - role: init
      tags: always

    - role: ldap-backend-selector
      when: enable_authentication | default(true)
      tags: always

    - role: image-download
      image_download_distribution: "{{ alternative_distribution }}"
      image_download_source: "{{ alternative_image_source | default('base') }}"
      when:
        - primary
        - download_base_image | default(false)
      tags: image-create

    - role: ansible/write_facts
      tags: always

    - role: image-create
      image_create_distribution: 'opensuse'
      when: primary
      tags: image-create

  environment:
    no_proxy: ".{{ domain }},{{ controller_ip }},{{ external_fqdn }},{{ controller_hostname }}"
    NO_PROXY: ".{{ domain }},{{ controller_ip }},{{ external_fqdn }},{{ controller_hostname }}"
  tags: image-create-ctrl


# Chroot image build
- hosts: image_build_chroot
  pre_tasks:
    - set_fact:
        in_image: true
        on_controller: false
        primary: false
      tags: always

    - set_fact:
        image_extend_docker: true
      when: alternative_image_source == 'docker'

    - set_fact:
        image_extend_osgrab: true
      when: alternative_image_source == 'osgrab'

    - set_fact:
        image_extend_scratch: true
      when:
        - not image_extend_docker | default(false)
        - not image_extend_osgrab | default(false)

  roles:
    - role: ansible/read_facts
      read_facts_cleanup: false
      tags: always

    - role: image-create
      image_create_distribution: 'opensuse'
      tags: image-create

  environment:
    no_proxy: ".{{ domain }},{{ controller_ip }},{{ external_fqdn }},{{ controller_hostname }}"
    NO_PROXY: ".{{ domain }},{{ controller_ip }},{{ external_fqdn }},{{ controller_hostname }}"
  tags: image-create-chroot
