# vars/Suse.yaml

openldap_packages:
  - openldap2
  - openldap2-client
  - cyrus-sasl

openldap_default_user: ldap
openldap_default_group: ldap

openldap_server_conf_path: /etc/openldap/slapd.d
openldap_server_dir_path: /var/lib/ldap
openldap_server_defaults_file: /etc/sysconfig/openldap

# SUSE uses the system CA bundle, not /etc/openldap/certs
openldap_tls_cacrt: /etc/ssl/ca-bundle.pem

# Group that owns system CA files
ssl_cert_group: trusted
