install_packages:
  - ipmitool
  - bash-completion
  - bc
  - bind-utils
  - bison
  - byacc
  - bzip2
  - createrepo_c
  - curl
  - dejavu-fonts
  - dmidecode
  - ethtool
  - gawk
  - gcc
  - gdisk
  - git
  - gzip
  - haveged
  - hdparm
  - htop
  - hwloc
  - hwloc-devel
  - infiniband-diags
  - iperf            # SUSE does NOT ship iperf3
  - kernel-default-devel
  - kernel-default   # SUSE does NOT ship kernel-default-headers
  - less
  - libevent-2_1-7
  - libevent-devel
  - libfabric
  - libgfortran5
  - libibverbs1
  - libpcap1
  - libpciaccess0
  - librdmacm1
  - libtool
  - sensors          # replaces lm_sensors
  - lsof
  - make
  - mcelog
  - picocom          # replaces minicom
  - mtr
  - netcat-openbsd
  - net-tools
  - numactl
  - libnuma1
  - libnuma-devel    # replaces numactl-devel
  - openssh
  - openssh-server
  - parted
  - patch
  - pciutils
  - perf
  - psmisc
  - rsync
  - screen
  - sg3_utils
  - smartmontools
  - sshpass
  - strace
  - sudo
  - sysstat
  - tcpdump
  - telnet
  - tftp
  - time
  - tmux
  - tree
  - usbutils
  - util-linux
  - vim
  - wget
  - xauth
  - mc
  - automake
  - expect           # provides mkpasswd.tcl
  - unzip
  - dosfstools
  - grub2-x86_64-efi
  - shim
  - efibootmgr
  - pbzip2           # replaces lbzip2
  - tar
  - dos2unix
  - jq
  - postfix
  - mailx            # replaces s-nail
