packages:
  - name: xcat-core
    version: "2.17.4-1.1"
  - name: slurmctld
    version: "24.05.0-1.1"
  - name: prometheus
    min_version: "2.45.0"
  - name: conserver
  - name: ipmitool
  - name: perl-JSON

dependencies:
  - package: xcat-core
    requires:
      - perl-JSON
