---
# Create the shared directory tree

- name: Register shared directory facts
  set_fact:
    "{{ item.name }}": "{{ item.path }}"
  loop: "{{ shared_tree_dirs }}"
  tags: always

- name: Create base shared directory structure
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ anarchy_root }}"
    - "{{ anarchy_local }}"
    - "{{ anarchy_data }}"
  when: item != ""

- name: Apply SELinux context to 
  file:
    path: "{{ anarchy_local }}"
    state: directory
    setype: home_root_t
    seuser: system_u
  when: ansible_selinux.status == "enabled"

- name: Create controller-specific directory structure
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ anarchy_sync }}"
    - "{{ anarchy_etc }}"
    - "{{ anarchy_sbin }}"
    - "{{ anarchy_ondemand }}"
    - "{{ anarchy_ssl }}"
  when: in_login_image | default(false) or ansible_connection not in 'chroot'

- name: Create high-availability directory
  file:
    path: "{{ anarchy_ha }}"
    state: directory
  when:
    - ha
    - anarchy_ha is defined
