---
- block:
  - name: Read raw facts file
    slurp:
      src: /facts.dat
    register: slurp_output

  - name: Decode facts
    set_fact:
      data: "{{ slurp_output.content | b64decode }}"

  - name: Load generic cluster facts
    set_fact:
      controller_hostname: "{{ data.controller_hostname }}"
      controller_ip: "{{ data.controller_ip }}"
      domain: "{{ data.domain }}"
      login_fqdn: "{{ data.login_fqdn }}"
      admin_group: "{{ data.admin_group }}"
      system_arch: "{{ data.system_arch }}"
      package_arch: "{{ data.package_arch }}"
      use_openldap: "{{ data.use_openldap }}"
      use_ds389: "{{ data.use_ds389 }}"

  - name: Remove facts file
    file:
      path: /facts.dat
      state: absent
    when: read_facts_cleanup | default(true)

  when: ansible_connection in 'chroot'
