---
- name: Get image path
  set_fact:
    image_path: "{{ shared_images }}/{{ image_name }}"

- name: Create directory for image
  file:
    name: "{{ image_path }}"
    state: directory

- name: Set facts
  set_fact:
    data:
      anarchy_ctrl_hostname: "{{ anarchy_ctrl_hostname }}"
      controller_ip: "{{ anarchy_ctrl_ip }}"
      domain: "{{ anarchy_domain }}"
      login_fqdn: "{{ login_fqdn }}"
      admin_group: "{{ admin_group | default('admins') }}"
      system_arch: "{{ system_arch }}"
      package_arch: "{{ package_arch }}"
      use_openldap: "{{ use_openldap | default(true) }}"
      use_ds389: "{{ use_ds389 | default(false) }}"

- name: Create facts file
  copy:
    dest: "{{ image_path }}/facts.dat"
    content: "{{ data }}"
