---
prometheus_slurm_exporter_version: "1.8.0"

# Vendor-neutral: fetch from the official GitHub releases
prometheus_slurm_exporter_binary_url: "https://github.com/rivosinc/prometheus-slurm-exporter/releases/download/v{{ prometheus_slurm_exporter_version }}/prometheus-slurm-exporter-{{ prometheus_slurm_exporter_version }}-{{ system_arch }}"

prometheus_slurm_exporter_web_listen_port: "14204"
prometheus_slurm_exporter_web_listen_host: "0.0.0.0"

prometheus_slurm_exporter_log_dir: "/var/log/prometheus"

prometheus_slurm_exporter_binary_install_dir: "/usr/local/bin"

prometheus_slurm_exporter_system_user: "prometheus-slurm-exporter"
prometheus_slurm_exporter_system_group: "prometheus"
prometheus_slurm_exporter_additional_system_groups: []
