---
###############################################################################
# 1. Load OS‑specific pacemaker vars
###############################################################################

- name: Load OS‑specific pacemaker vars
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yaml"
    - "{{ ansible_os_family }}{{ ansible_distribution_major_version }}.yaml"
    - "{{ ansible_os_family }}.yaml"     # RedHat.yaml, Suse.yaml, Debian.yaml
    - "default.yaml"
  no_log: false

###############################################################################
# 2. Dispatch to OS‑specific tasks
###############################################################################

- name: Run Pacemaker stack for SUSE
  include_tasks: Suse.yml
  when: ansible_os_family == "Suse"

- name: Run Pacemaker stack for RedHat
  include_tasks: RedHat.yml
  when: ansible_os_family == "RedHat"

- name: Run Pacemaker stack for Debian/Ubuntu
  include_tasks: Debian.yml
  when: ansible_os_family == "Debian"
