---

- set_fact:
    this_anarchy_ctrl_hostname: "{{ inner_loop_var }}"
  when: 
    - this_anarchy_ctrl_hostname is not defined
    - inner_loop_var != ""
    - (inner_loop_var == ansible_hostname) or (inner_loop_var == ansible_fqdn) or (inner_loop_var.split('.')[0] == ansible_hostname)
